baseURL: "https://example.org/"
languageCode: en-gb
title: Welcome to Tecssolutions
theme: ["PaperMod"]

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

params:
  homeInfoParams:
    Title: "Welcome to tecsolutions.co.uk."
    Content: Welcome to tecsolutions.co.uk
  socialIcons:
    - name: facebook
      url: "https://www.facebook.com/simon.mcnair"
    - name: github
      url: "https://github.com/simonmcnair/"
    - name: linkedin
      url: "https://www.linkedin.com/in/simonmcnair/"

  cover:
    linkFullImages: false

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30