---
baseURL: "www.tecssolutions.co.uk"
languageCode: en-gb
title: Tecssolutions.co.uk
theme: ["PaperMod"]

# git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1

# module:
#   imports:
#   - path: github.com/adityatelange/hugo-PaperMod

params:
  homeInfoParams:
    Title: "Welcome"
    Content: Based in Market Harborough Tecssolutions is your one stop computing consultancy.
  env: production
  socialIcons:
    - name: facebook
      url: "https://www.facebook.com/simon.mcnair"
    - name: github
      url: "https://github.com/simonmcnair/"
    - name: linkedin
      url: "https://www.linkedin.com/in/simonmcnair/"
  websiteterms: /assets/termsandconditions.html
  privacypolicy: /assets/privacypolicy.html
#  footer:
#    - text: "This is footer text - markdown suported"
#    - hideCopyright: true
  cover:
    linkFullImages: false

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
